package main

import (
	"github.com/mojtabafarzaneh/social_media/src/cmd"
	"github.com/mojtabafarzaneh/social_media/src/db"

	_ "github.com/swaggo/echo-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.
)

func init() {
	db.ConnectToDB()
}

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

func main() {

	cmd.Execute()
}
